[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8080
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2ca02c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false